---
# tasks file for update_tower_inventory
- name: Update tower inventory
  tower_inventory:
    name: "{{ ec2_name_prefix }} AWS Inventory"
    organization: "Empire"
    state: present
    validate_certs: no
    tower_username: admin
    tower_password: emergent-42-automaton